// 配置文件
const CONFIG = {
    MAX_FILE_SIZE: 10 * 1024 * 1024, // 10MB
    SUPPORTED_IMAGE_FORMATS: ['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'image/bmp'],
    SUPPORTED_IMAGE_MIME_TYPES: ['image/jpeg', 'image/png', 'image/webp', 'image/gif', 'image/bmp'],
    DEFAULT_QR_SIZE: 200,
    TOOL_NAMES: {
        imageConverter: '图片格式转换',
        md5: 'MD5加密',
        simplifiedTraditional: '简繁体转换',
        qrcode: '二维码生成',
        base64: 'Base64编码/解码',
        urlCodec: 'URL编码/解码',
        colorConverter: '颜色格式转换',
        timestamp: '时间戳转换'
    }
};

// DOM 元素选择器
const SELECTORS = {
    toast: '#toast',
    navList: '#navList',
    toolCards: '.tool-card',
    toolPanels: '.tool-panel',
    heroSection: '#heroSection',
    toolsSection: '#toolsSection',
    workspaceTitle: '#workspaceTitle',
    backBtn: '.back-btn',
    imageUploadArea: '#imageUploadArea',
    imageFileInput: '#imageFileInput',
    imagePreviewContainer: '#imagePreviewContainer',
    imagePreview: '#imagePreview',
    formatSelect: '#formatSelect',
    targetFormat: '#targetFormat',
    imageResultArea: '#imageResultArea',
    convertedImage: '#convertedImage',
    md5Input: '#md5Input',
    md5Result: '#md5Result',
    md5Value: '#md5Value',
    stInput: '#stInput',
    stOutput: '#stOutput',
    stResultBox: '#stResultBox',
    qrcodeInput: '#qrcodeInput',
    qrcodeSize: '#qrcodeSize',
    qrcodeResult: '#qrcodeResult',
    qrcodeContainer: '#qrcodeContainer',
    base64Input: '#base64Input',
    base64Output: '#base64Output',
    base64ResultBox: '#base64ResultBox',
    base64EncodeBtn: '#base64EncodeBtn',
    base64DecodeBtn: '#base64DecodeBtn',
    urlInput: '#urlInput',
    urlOutput: '#urlOutput',
    urlResultBox: '#urlResultBox',
    urlEncodeBtn: '#urlEncodeBtn',
    urlDecodeBtn: '#urlDecodeBtn',
    colorPreview: '#colorPreview',
    colorInput: '#colorInput',
    colorOutputs: '#colorOutputs',
    hexOutput: '#hexOutput',
    rgbOutput: '#rgbOutput',
    hslOutput: '#hslOutput',
    currentTimestamp: '#currentTimestamp',
    currentDate: '#currentDate',
    timestampInput: '#timestampInput',
    dateInput: '#dateInput',
    timestampResult: '#timestampResult',
    timestampResultValue: '#timestampResultValue'
};